/Users/magnus/code/pycket-bench/pycket/pycket-c src/meteor.rkt 200000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/meteor.rkt 200000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/meteor.rkt 200000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/sumcol.rkt sumcol-20000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/sumcol.rkt sumcol-20000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/sumcol.rkt sumcol-20000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nbody-vec.rkt 15000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nbody-vec.rkt 15000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nbody-vec.rkt 15000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/binarytrees-generic.rkt 17
/Users/magnus/code/pycket-bench/pycket/pycket-c src/binarytrees-generic.rkt 17
/Users/magnus/code/pycket-bench/pycket/pycket-c src/binarytrees-generic.rkt 17
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nbody.rkt 8000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nbody.rkt 8000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nbody.rkt 8000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/hash.rkt 4000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/hash.rkt 4000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/hash.rkt 4000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/pidigits.rkt 7000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/pidigits.rkt 7000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/pidigits.rkt 7000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/heapsort.rkt 1500000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/heapsort.rkt 1500000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/heapsort.rkt 1500000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nbody-vec-generic.rkt 15000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nbody-vec-generic.rkt 15000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nbody-vec-generic.rkt 15000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/moments.rkt moments-2000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/moments.rkt moments-2000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/moments.rkt moments-2000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/spectralnorm-generic.rkt 3000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/spectralnorm-generic.rkt 3000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/spectralnorm-generic.rkt 3000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fibo.rkt 42
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fibo.rkt 42
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fibo.rkt 42
/Users/magnus/code/pycket-bench/pycket/pycket-c src/matrix.rkt 25000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/matrix.rkt 25000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/matrix.rkt 25000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fannkuch-redux.rkt 10
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fannkuch-redux.rkt 10
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fannkuch-redux.rkt 10
/Users/magnus/code/pycket-bench/pycket/pycket-c src/ary.rkt 1700000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/ary.rkt 1700000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/ary.rkt 1700000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/wordfreq.rkt sumcol-20000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/wordfreq.rkt sumcol-20000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/wordfreq.rkt sumcol-20000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nestedloop.rkt 35
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nestedloop.rkt 35
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nestedloop.rkt 35
/Users/magnus/code/pycket-bench/pycket/pycket-c src/mandelbrot-generic.rkt 5000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/mandelbrot-generic.rkt 5000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/mandelbrot-generic.rkt 5000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fannkuch.rkt 10
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fannkuch.rkt 10
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fannkuch.rkt 10
/Users/magnus/code/pycket-bench/pycket/pycket-c src/pidigits1.rkt 20000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/pidigits1.rkt 20000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/pidigits1.rkt 20000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/strcat.rkt 110000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/strcat.rkt 110000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/strcat.rkt 110000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fannkuch-redux-generic.rkt 10
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fannkuch-redux-generic.rkt 10
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fannkuch-redux-generic.rkt 10
/Users/magnus/code/pycket-bench/pycket/pycket-c src/wc.rkt sumcol-20000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/wc.rkt sumcol-20000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/wc.rkt sumcol-20000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/sieve.rkt 50000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/sieve.rkt 50000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/sieve.rkt 50000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/ackermann.rkt 12
/Users/magnus/code/pycket-bench/pycket/pycket-c src/ackermann.rkt 12
/Users/magnus/code/pycket-bench/pycket/pycket-c src/ackermann.rkt 12
/Users/magnus/code/pycket-bench/pycket/pycket-c src/binarytrees.rkt 17
/Users/magnus/code/pycket-bench/pycket/pycket-c src/binarytrees.rkt 17
/Users/magnus/code/pycket-bench/pycket/pycket-c src/binarytrees.rkt 17
/Users/magnus/code/pycket-bench/pycket/pycket-c src/spectralnorm.rkt 3000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/spectralnorm.rkt 3000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/spectralnorm.rkt 3000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/hash2.rkt 6000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/hash2.rkt 6000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/hash2.rkt 6000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fasta-generic.rkt 100000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fasta-generic.rkt 100000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fasta-generic.rkt 100000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nsieve.rkt 12
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nsieve.rkt 12
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nsieve.rkt 12
/Users/magnus/code/pycket-bench/pycket/pycket-c src/regexmatch.rkt regexmatch-1000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/regexmatch.rkt regexmatch-1000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/regexmatch.rkt regexmatch-1000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nsievebits.rkt 12
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nsievebits.rkt 12
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nsievebits.rkt 12
/Users/magnus/code/pycket-bench/pycket/pycket-c src/lists.rkt 2000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/lists.rkt 2000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/lists.rkt 2000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/partialsums.rkt 15000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/partialsums.rkt 15000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/partialsums.rkt 15000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/random.rkt 250000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/random.rkt 250000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/random.rkt 250000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/recursive.rkt 12
/Users/magnus/code/pycket-bench/pycket/pycket-c src/recursive.rkt 12
/Users/magnus/code/pycket-bench/pycket/pycket-c src/recursive.rkt 12
/Users/magnus/code/pycket-bench/pycket/pycket-c src/spellcheck.rkt ulysses
/Users/magnus/code/pycket-bench/pycket/pycket-c src/spellcheck.rkt ulysses
/Users/magnus/code/pycket-bench/pycket/pycket-c src/spellcheck.rkt ulysses
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fasta.rkt 100000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fasta.rkt 100000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/fasta.rkt 100000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/mandelbrot.rkt 5000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/mandelbrot.rkt 5000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/mandelbrot.rkt 5000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nbody-generic.rkt 8000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nbody-generic.rkt 8000000
/Users/magnus/code/pycket-bench/pycket/pycket-c src/nbody-generic.rkt 8000000
